# -*- coding: utf-8 -*-
"""Analisis de diabetes con t student y regresion logistica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wr_IF0TjVP94VxAvBMmDhf0M3h7iTKa9
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('diabetes.csv')

df

df.isnull().sum()

df.describe()

df.info()

(df[['Insulin', 'Glucose']] == 0).sum()

df_clean = df[df['Insulin'] != 0]
df_clean

df_clean['Insulin'].corr(df_clean['Glucose'])

df_clean.corr()

import statsmodels.api as sm

X = df[['Glucose', 'BMI', 'Age', 'Insulin']]
X = sm.add_constant(X)
y = df['Outcome']

modelo = sm.Logit(y, X).fit()
print(modelo.summary())

# el modelo explica el 24% de probabilidad mediante el r¨2, además si aplicamos el odds ratio a
#l coeficiente de la glucose podemos observar OR=e0.034≈1.035, este resultado explica que aumenta la probabilidad
# de tener diabetes en un 3.3% al consumir glucose, tambien otros valores como el BMI con su coeficiente aumenta en un 8.8% sobre
#quienes tienen glucosa y cada año adicional de edad aumenta el riesgo en ~2.9%

from scipy.stats import ttest_ind

grupo0 = df[df['Outcome'] == 0]['Glucose']
grupo1 = df[df['Outcome'] == 1]['Glucose']

ttest_ind(grupo0, grupo1, equal_var=False)

#Se rechaza hipotesis nula de igualdad con la prueba T student extremadamente fuerte, con la t:-13.75
#lo que indica que las personas con màs diabetes tienen mayor glucosa