# -*- coding: utf-8 -*-
"""Prediccion regresion lineal con widgets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RzuUCjtfhImDYqrtWyzNZ834d5W7cBJM
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Cars_Multi555.csv')

df

df.info()

df.describe()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
#definicion de caracteristicas
X = df[['weight','cylinders','mpg','model']]
y = df ['acceleration']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

model.score(X_test, y_test)

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=1000,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_score = rf_model.score(X_test, y_test)
print(rf_score)

#este modelo de arboles de decisión no predice tan bien pero funciona para mi objetivo de aprendizaje
import ipywidgets as widgets
from IPython.display import display

# Widgets
weight_widget = widgets.FloatText(description='weight_', value=3504)
cylinders_widget = widgets.FloatText(description='cylinders_', value=8)
mpg_widget = widgets.FloatText(description='mpg_', value=18.0)
model_widget = widgets.FloatText(description='model_', value=70)

button = widgets.Button(description='Predict')
output = widgets.Output()

# Función del botón
def Pulsar_boton(b):
    with output:
        output.clear_output()

        weight_ = weight_widget.value
        cylinders_ = cylinders_widget.value
        mpg_ = mpg_widget.value
        model_year_ = model_widget.value

        input_data = pd.DataFrame(
            [[weight_, cylinders_, mpg_, model_year_]],
            columns=['weight', 'cylinders', 'mpg', 'model']
        )

        prediction = rf_model.predict(input_data)[0]
        print(f'La predicción es: {prediction:.2f}')

# Conectar botón
button.on_click(Pulsar_boton)

# boton
display(
    weight_widget,
    cylinders_widget,
    mpg_widget,
    model_widget,
    button,
    output
)

